# Generated by Django 3.1.6 on 2021-05-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('inpchat', models.TextField()),
                ('replychat', models.TextField()),
                ('sessionuid', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sentiments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionno', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('sessionuid', models.CharField(max_length=100)),
                ('sentiment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
