# Generated by Django 3.1.6 on 2021-05-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deppy', '0002_auto_20210521_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentiments',
            name='sessionno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
