# Generated by Django 3.1.6 on 2021-05-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deppy', '0003_auto_20210521_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentiments',
            name='sentiment',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
